export const FETCH_CHARACTER = '[FETCH] CHARACTER';
export const SUCCESS_CHARACTER = '[SUCCESS] CHARACTER';
export const ERROR_CHARACTER = '[ERROR] CHARACTER';
export const UPDATE_NUM_PAGE_CHARACTER = '[UPDATE] NUM PAGE CHARACTER';
